captainVersion: 4
services:
    $$cap_appname-db:
        image: bitminds/nextjs-monitoring
        restart: always
        environment:
            NEXT_URL: $$cap_next_url
            PROMETHEUS_IP: $$cap_prometheus_ip
        caproverExtra:
            notExposeAsWebApp: 'false'
caproverOneClickApp:
    variables:
        - id: $$cap_next_url
          label: Next.js Application Url
          defaultValue: ''
          description: ''
        - id: $$cap_prometheus_ip
          label: Prometheus Instance IP
          description: ''
    displayName: Next.js Prometheus Exporter
    description: Next.js Prometheus Exporter allows to export Next.js Analytics to Prometheus
